import { eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { actor, canAccessLead } from "@/server/auth";
import { db } from "@/server/db";
import { activities, calls, followUps, leads } from "@/server/schema";
import { errorResponse } from "@/server/http";
import { broadcaster } from "@/server/events";
const outcomes = ["SPOKE", "NO_ANSWER", "BUSY", "NOT_REACHABLE", "WRONG_NUMBER", "CALL_BACK_LATER", "OTHER"] as const;
const input = z.object({ outcome: z.enum(outcomes), duration: z.coerce.number().int().min(0).nullable().optional(), leadResponse: z.string().nullable(), interestLevel: z.string().nullable(), salespersonAction: z.string().nullable(), nextAction: z.string().nullable(), nextFollowUpAt: z.coerce.date().nullable(), notes: z.string().nullable() }).superRefine((value, ctx) => { if (value.outcome === "SPOKE") for (const field of ["leadResponse", "interestLevel", "salespersonAction", "nextAction", "nextFollowUpAt", "notes"] as const) if (!value[field]) ctx.addIssue({ code: "custom", path: [field], message: "Required when you spoke with the lead." }); });
export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const user = await actor(); const { id } = await params; const [lead] = await db.select().from(leads).where(eq(leads.id, id)); if (!lead) return NextResponse.json({ error: "Lead not found" }, { status: 404 }); canAccessLead(user, lead.assigneeId); const data = input.parse(await request.json()); const spoke = data.outcome === "SPOKE"; const newStatus = spoke && ["NEW", "ASSIGNED"].includes(lead.status) ? "CONTACTED" : lead.status; await db.transaction(async tx => { await tx.insert(calls).values({ leadId: id, createdBy: user.id, duration: data.duration ?? null, callType: "OUTBOUND", outcome: data.outcome, interestLevel: data.interestLevel, leadResponse: data.leadResponse, salespersonAction: data.salespersonAction, nextAction: data.nextAction, nextFollowUpAt: data.nextFollowUpAt, notes: data.notes }); await tx.update(leads).set({ status: newStatus, lastContactAt: spoke ? new Date() : lead.lastContactAt, leadResponse: data.leadResponse ?? lead.leadResponse, salespersonAction: data.salespersonAction ?? lead.salespersonAction, nextAction: data.nextAction ?? lead.nextAction, nextFollowUpAt: data.nextFollowUpAt ?? lead.nextFollowUpAt, updatedAt: new Date() }).where(eq(leads.id, id)); if (data.nextFollowUpAt) await tx.insert(followUps).values({ leadId: id, assigneeId: lead.assigneeId || user.id, dueAt: data.nextFollowUpAt, reason: data.nextAction || `Call outcome: ${data.outcome}`, notes: data.notes }); await tx.insert(activities).values({ leadId: id, actorId: user.id, type: "CALL_LOGGED", description: `Call attempt recorded: ${data.outcome.replaceAll("_", " ")}` }); }); broadcaster.broadcast("call:logged", { leadId: id, outcome: data.outcome, callerId: user.id, occurredAt: new Date().toISOString() }); broadcaster.broadcast("lead:updated", { id, status: newStatus, updatedAt: new Date().toISOString() }); return NextResponse.json({ ok: true }); } catch (error) { return errorResponse(error); } }
