"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
const options = [["SPOKE", "Spoke"], ["NO_ANSWER", "No answer"], ["BUSY", "Busy"], ["CALL_BACK_LATER", "Call back"], ["WRONG_NUMBER", "Wrong number"], ["NOT_REACHABLE", "Not reachable"], ["OTHER", "Other"]] as const;
export function CallOutcomeForm({ leadId }: { leadId: string }) {
  const [outcome, setOutcome] = useState<string>(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const router = useRouter(); const spoke = outcome === "SPOKE";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!outcome) return setMessage("Choose the actual call outcome."); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form) as Record<string, string | null>; payload.outcome = outcome; for (const key of ["leadResponse", "interestLevel", "salespersonAction", "nextAction", "nextFollowUpAt", "notes", "duration"]) if (!payload[key]) payload[key] = null; setSaving(true); const response = await fetch(`/api/leads/${leadId}/calls`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); setSaving(false); if (!response.ok) return setMessage(body.error || "Please complete the required fields."); setMessage("Call attempt saved."); router.refresh(); event.currentTarget.reset(); setOutcome(""); }
  return <form className="call-form" onSubmit={submit}><h3>Record call outcome</h3><p>A call only counts as contact after you save its actual result.</p><div className="outcome-buttons">{options.map(([value, title]) => <button type="button" className={outcome === value ? "chosen" : ""} onClick={() => setOutcome(value)} key={value}>{title}</button>)}</div><label>Duration in seconds <input name="duration" type="number" min="0" /></label>{spoke && <><label>Lead response <input name="leadResponse" required /></label><label>Interest level <select name="interestLevel" required><option value="">Select</option><option>Interested</option><option>Qualified</option><option>Not interested</option></select></label><label>What you did <input name="salespersonAction" required /></label></>}<label>Next action <input name="nextAction" required={spoke} /></label><label>Next follow-up <input name="nextFollowUpAt" type="datetime-local" required={spoke} /></label><label>Notes <textarea name="notes" required={spoke} /></label><button className="primary" disabled={saving}>{saving ? "Saving…" : "Save call attempt"}</button>{message && <span className="form-message">{message}</span>}</form>;
}
