import { eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { actor, canAccessLead } from "@/server/auth";
import { db } from "@/server/db";
import { activities, followUps, leads, notifications } from "@/server/schema";
import { errorResponse } from "@/server/http";
import { broadcaster } from "@/server/events";
const input = z.object({ outcome: z.string().min(2), leadResponse: z.string().min(1), salespersonAction: z.string().min(1), nextAction: z.string().nullable(), nextFollowUpAt: z.coerce.date().nullable(), notes: z.string().nullable() });
export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const user = await actor(); const { id } = await params; const [followUp] = await db.select().from(followUps).where(eq(followUps.id, id)); if (!followUp) return NextResponse.json({ error: "Follow-up not found" }, { status: 404 }); const [lead] = await db.select().from(leads).where(eq(leads.id, followUp.leadId)); if (!lead) return NextResponse.json({ error: "Lead not found" }, { status: 404 }); canAccessLead(user, lead.assigneeId); const data = input.parse(await request.json()); await db.transaction(async tx => { await tx.update(followUps).set({ status: "COMPLETED", completedAt: new Date(), notes: data.notes, updatedAt: new Date() }).where(eq(followUps.id, id)); await tx.update(leads).set({ lastContactAt: new Date(), leadResponse: data.leadResponse, salespersonAction: data.salespersonAction, nextAction: data.nextAction, nextFollowUpAt: data.nextFollowUpAt, updatedAt: new Date() }).where(eq(leads.id, lead.id)); if (data.nextFollowUpAt) await tx.insert(followUps).values({ leadId: lead.id, assigneeId: lead.assigneeId || user.id, dueAt: data.nextFollowUpAt, reason: data.nextAction || "Follow-up required", notes: data.notes }); await tx.insert(activities).values({ leadId: lead.id, actorId: user.id, type: "FOLLOW_UP_COMPLETED", description: `Completed follow-up: ${data.outcome}` }); if (data.nextFollowUpAt) await tx.insert(notifications).values({ userId: lead.assigneeId || user.id, type: "FOLLOW_UP", title: "Follow-up scheduled", message: `${lead.companyName}: ${data.nextAction || "Follow-up required"}` }); }); broadcaster.broadcast("followup:completed", { id, leadId: lead.id, completedAt: new Date().toISOString() }); broadcaster.broadcast("lead:updated", { id: lead.id, updatedAt: new Date().toISOString() }); return NextResponse.json({ ok: true }); } catch (error) { return errorResponse(error); } }
