import { and, asc, desc, eq, ilike, or, sql } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { actor } from "@/server/auth";
import { db } from "@/server/db";
import { activities, leads } from "@/server/schema";
import { errorResponse } from "@/server/http";
const input = z.object({ companyName: z.string().min(2), contactName: z.string().min(2), email: z.email().optional(), phone: z.string().optional(), source: z.string().optional(), industry: z.string().optional(), priority: z.enum(["LOW","MEDIUM","HIGH","URGENT"]).default("MEDIUM"), assigneeId: z.string().optional(), nextAction: z.string().optional(), nextFollowUpAt: z.coerce.date().optional() });
export async function GET(request: NextRequest) { try { const user = await actor(), p = request.nextUrl.searchParams, page = Math.max(1, Number(p.get("page") || 1)), size = Math.min(100, Number(p.get("size") || 25)), search = p.get("search"), where = and(user.role === "SALESPERSON" ? eq(leads.assigneeId, user.id) : undefined, p.get("status") ? eq(leads.status, p.get("status") as typeof leads.status.enumValues[number]) : undefined, p.get("priority") ? eq(leads.priority, p.get("priority") as typeof leads.priority.enumValues[number]) : undefined, search ? or(ilike(leads.companyName, `%${search}%`), ilike(leads.contactName, `%${search}%`), ilike(leads.email, `%${search}%`), ilike(leads.phone, `%${search}%`), ilike(leads.location, `%${search}%`)) : undefined); const [items, total] = await Promise.all([db.select().from(leads).where(where).orderBy(desc(leads.updatedAt)).limit(size).offset((page - 1) * size), db.select({ count: sql<number>`count(*)` }).from(leads).where(where)]); return NextResponse.json({ items, page, size, total: Number(total[0].count) }); } catch (e) { return errorResponse(e); } }
export async function POST(request: NextRequest) { try { const user = await actor(), data = input.parse(await request.json()); if (user.role !== "FOUNDER" && data.assigneeId && data.assigneeId !== user.id) throw new Error("FORBIDDEN"); const [lead] = await db.transaction(async tx => { const [created] = await tx.insert(leads).values({ ...data, createdBy: user.id, assigneeId: data.assigneeId || user.id, status: data.assigneeId ? "ASSIGNED" : "NEW" }).returning(); await tx.insert(activities).values({ leadId: created.id, actorId: user.id, type: "LEAD_CREATED", description: `Created lead ${created.companyName}` }); return [created]; }); return NextResponse.json(lead, { status: 201 }); } catch (e) { return errorResponse(e); } }
